import { useUser } from '@clerk/nextjs';
import { type NextPage } from 'next';
import Head from 'next/head';
import { api } from '~/utils/api';
import dayjs from 'dayjs';
import relativeTime from 'dayjs/plugin/relativeTime';
import { LoadingPage } from '~/components/ui/loading';
import { useState } from 'react';
import { useToast } from '~/components/use-toast';
import {
    Card,
    CardContent,
    CardDescription,
    CardHeader,
    CardTitle,
} from '~/components/ui/card';
import { Input } from '~/components/ui/input';
import { Button } from '~/components/ui/button';
import { Loader2 } from 'lucide-react';
import { ScrollArea } from '~/components/ui/scroll-area';
import { PostView } from '~/components/postview';

dayjs.extend(relativeTime);

const CreatePostWizard = () => {
    const [inputValue, setInputValue] = useState('');
    const { toast } = useToast();
    const { user } = useUser();

    const ctx = api.useContext();

    const { mutate, isLoading: isPosting } = api.posts.create.useMutation({
        onSuccess: () => {
            setInputValue('');
            void ctx.posts.getAll.invalidate();
        },
        onError: (error) => {
            const errorMesage = error.data?.zodError?.fieldErrors.content;

            if (errorMesage && errorMesage[0]) {
                toast({ title: 'Error!', description: errorMesage[0] });
            } else {
                toast({
                    title: 'Error!',
                    description: 'Failed to create post',
                });
            }
        },
    });

    const sendPost = () => {
        if (!user) {
            toast({ title: 'Error', description: 'Log in first' });
            return;
        }
        mutate({ content: inputValue });
    };

    const handleKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
        if (e.key !== 'Enter') return;

        if (inputValue.length === 0) {
            toast({ title: 'Error!', description: 'Post cannot be empty' });
            return;
        }

        sendPost();
    };

    return (
        <Card>
            <CardHeader>
                <CardTitle>Создать пост</CardTitle>
                <CardDescription>
                    Создайте пост, чтобы его все видели!
                </CardDescription>
                <CardContent className="flex items-center gap-2 p-2">
                    <Input
                        value={inputValue}
                        onChange={(e) => setInputValue(e.target.value)}
                        type="text"
                        placeholder="Ваш текст"
                        onKeyDown={handleKeyDown}
                    />
                    {user ? (
                        <Button
                            disabled={isPosting}
                            onClick={sendPost}
                            className="grid place-items-center"
                        >
                            {isPosting ? (
                                <Loader2 className="mx-1 h-4 w-4 animate-spin" />
                            ) : (
                                'Post'
                            )}
                        </Button>
                    ) : (
                        <Button
                            disabled={true}
                            className={'cursor-not-allowed'}
                        >
                            Подтвердить
                        </Button>
                    )}
                </CardContent>
            </CardHeader>
        </Card>
    );
};

const Feed = () => {
    const { data, isLoading: postsLoading } = api.posts.getAll.useQuery();
    const { toast } = useToast();

    const ctx = api.useContext();

    const onSuccess = () => {
        toast({
            title: 'Success!',
            description: `Post deleted`,
        });
        void ctx.posts.getAll.invalidate();
    };

    if (postsLoading) return <LoadingPage />;

    if (!data) return <h1>No data</h1>;

    return (
        <ScrollArea className={'h-screen w-full rounded-md border'}>
            <div className="p-4">
                <h1>Posts</h1>
                {data.map((fullpost) => (
                    <PostView
                        key={fullpost.post.id}
                        {...fullpost}
                        onSuccess={onSuccess}
                    />
                ))}
            </div>
        </ScrollArea>
    );
};

const Home: NextPage = () => {
    const { isLoaded: userLoaded } = useUser();

    api.posts.getAll.useQuery();

    if (!userLoaded) return <div />;

    return (
        <>
            <Head>
                <title>Chichirp</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="space-y-4">
                <CreatePostWizard />
                <Feed />
            </main>
        </>
    );
};

export default Home;
