import { type NextPage } from 'next';
import Head from 'next/head';

const SinglePostPage: NextPage = () => {
    return (
        <>
            <Head>
                <title>Single post page</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="shortcut icon" href="/favicon.ico" />
            </Head>
            <main>
                <h1>Single post page</h1>
            </main>
        </>
    );
};

export default SinglePostPage;
