import { type GetStaticProps, type NextPage } from 'next';
import Head from 'next/head';
import { PostView } from '~/components/postview';
import { generateSSRHelper } from '~/server/helpers/ssgHelper';
// import { useRouter } from 'next/router';
import { api } from '~/utils/api';

import dayjs from 'dayjs';
import 'dayjs/locale/ru';

import relativeTime from 'dayjs/plugin/relativeTime';

import { CommentView } from '~/components/commentview';
import { LoadingPage } from '~/components/ui/loading';
import { ScrollArea } from '~/components/ui/scroll-area';
import { Input } from '~/components/ui/input';
import { Button } from '~/components/ui/button';
import { useState } from 'react';
import { useToast } from '~/components/use-toast';
// import { useUser } from '@clerk/nextjs';

dayjs.extend(relativeTime);
dayjs.locale('ru');

const CreateCommentWizard = ({ postId }: { postId: string }) => {
    const [inputValue, setInputValue] = useState('');
    const { toast } = useToast();
    // const { user } = useUser();
    const ctx = api.useContext();

    const { mutate, isLoading: commentCreating } =
        api.comments.create.useMutation({
            onSuccess: () => {
                setInputValue('');
                toast({
                    title: 'Success!',
                    description: 'Комментарий успешно создан',
                });
                void ctx.comments.getAll.invalidate();
            },
            onError: (error) => {
                const errorMesage = error.data?.zodError?.fieldErrors.content;

                if (errorMesage && errorMesage[0]) {
                    toast({ title: 'Error!', description: errorMesage[0] });
                } else {
                    toast({
                        title: 'Error!',
                        description: 'Ошибка в создании комментария',
                    });
                }
            },
        });

    const createPost = () => {
        mutate({ comment: inputValue, postId });
    };

    const handleButtonClick = () => {
        createPost();
    };

    const handleKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
        if (e.key !== 'Enter') return;
        createPost();
    };

    return (
        <div className="rounded-md border p-4">
            <h1 className="mb-2 text-center font-semibold">
                Напишите комментарий!
            </h1>
            <div className="flex gap-2">
                <Input
                    placeholder="Ваш комментарий"
                    value={inputValue}
                    onChange={(e) => setInputValue(e.target.value)}
                    onKeyDown={handleKeyDown}
                />
                <Button onClick={handleButtonClick} disabled={commentCreating}>
                    Отправить
                </Button>
            </div>
        </div>
    );
};

const SinglePostPage: NextPage<{ id: string }> = ({ id }) => {
    const { data: postWithAutor } = api.posts.getById.useQuery({ id });
    const { data: commentsData, isLoading: commentsLoading } =
        api.comments.getAll.useQuery({ postId: id });

    // const router = useRouter();

    // const ctx = api.useContext();

    const onSuccess = () => {
        // void ctx.posts.getAll.invalidate();
        // void router.push('/');
    };

    if (!postWithAutor) return null;

    return (
        <>
            <Head>
                <title>Single post page</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="shortcut icon" href="/favicon.ico" />
            </Head>
            <main className="h-full space-y-2 justify-self-start ">
                <div className="rounded-md border p-6">
                    <h1 className="ml-2 text-lg font-medium">Пост</h1>
                    <PostView
                        {...postWithAutor}
                        onSuccess={onSuccess}
                        isSeparatorNeeded={false}
                    />
                </div>
                <CreateCommentWizard postId={postWithAutor.post.id} />
                {commentsLoading && <LoadingPage />}
                <ScrollArea className={'w-full rounded-md border'}>
                    <div className="p-4">
                        {!commentsData || commentsData?.length === 0 ? (
                            <h1 className="ml-2 text-center text-base font-medium">
                                У этого поста пока нет комментариев. <br />
                                Будьте первым!
                            </h1>
                        ) : (
                            <div>
                                {commentsData.map((item) => (
                                    <CommentView
                                        {...item}
                                        key={item.comment.id}
                                    />
                                ))}
                            </div>
                        )}
                    </div>
                </ScrollArea>
            </main>
        </>
    );
};

export const getStaticProps: GetStaticProps = async (context) => {
    const helpers = generateSSRHelper();

    const id = context.params?.id;

    if (typeof id !== 'string') throw new Error('id must be a string');

    await helpers.posts.getById.prefetch({ id });

    return {
        props: {
            trpcState: helpers.dehydrate(),
            id,
        },
    };
};

export const getStaticPaths = () => {
    return {
        paths: [],
        fallback: 'blocking',
    };
};

export default SinglePostPage;
